---
title: "PreParcial"
output: html_document
date: '2022-05-09'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
Se quiere comparar tratamientos
*respuesta:cannabinoide
*factor(3niveles):genotipo

por lo menos uno es diferente

*diseño factorial simple_con arreglo completamente al azar
```

```{r}
set.seed(2021)

udc=c(
  rnorm(n=24,mean=5.0,sd=0.20),
  rnorm(n=24,mean=5.0,sd=0.20),
  rnorm(n=24,mean=5.0,sd=0.20)
            )
genotipo=gl(n=3,k=24,length=72,c("gen1","gen2","gen3"))

df1=data.frame(genotipo,udc)
head(df1)
```

```{r}
xy=expand.grind(x=1.8,y=1.9)
alet=sample(72)
df1discord_x=xy$x[alet]
df1discord_y=xy$y[alet]

library(ggplot2)
ggplot(df1)+
  aes(cord_x,cord_y,fill=genotipo)+
  geom_tile(color="black",width=0.8,height=0.8)+
  #geom_text((aes(label=genotipo),color))
```
```{r}
ggplot(df1)+
  aes(genotipo,udc,fill=genotipo)+
  geom_boxplot()+
  geom_hline(yintercept = 5.2)
```
```{r}
library(dplyr)
df1 %>%
  group_by(genotipo)%>%
  summarise(media=mean(udc),
            des=sd(udc),
            cv=100+des/media)

```

title: "CE"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Se quieren comparar tratamietnos

Diseño Factorial Simple Completamente al Azar

* Respuesta: Canabinoide (udc)
* Factor (3 niveles): Genotipo (gen1, gen2, gen3)

$$H_0: \mu_{gen_1} = \mu_{gen_2} = \mu_{gen_3}$$



```{r}
set.seed(123)

udc = c(
  rnorm(n = 24, mean = 5.0, sd = 0.20),
  rnorm(n = 24, mean = 5.6, sd = 0.22),
  rnorm(n = 24, mean = 5.8, sd = 0.18)
)
genotipo = gl(n = 3, k = 24, length = 72, c('gen1','gen2','gen3'))

df1 = data.frame(genotipo, udc)
head(df1)
```

```{r}
xy = expand.grid(x=1:8, y=1:9)
aleat = sample(72)
df1$cord_x = xy$x[aleat]
df1$cord_y = xy$y[aleat]

library(ggplot2)
ggplot(df1)+
  aes(cord_x, cord_y, fill=udc)+
  geom_tile(color='black', width=0.8, height=0.8)+
  geom_text(aes(label=genotipo), color='white', size=5)
```

### Estadística descriptiva

```{r}
ggplot(df1)+
  aes(genotipo, udc, fill=genotipo)+
  geom_boxplot()+
  geom_hline(yintercept = 5.2)
```

```{r}
library(dplyr)

df1 %>% 
  group_by(genotipo) %>% 
  summarise(media=mean(udc),
            desv=sd(udc),
            cv=100*desv/media)
```

### Estadistica Inferencial

Modelo:

$$y_{ij} = \mu + \tau_i + \epsilon_{ij}\\
i=1,2,3;~j=1,2,\dots,24$$

**Tecnica estadistica**: Análisis de Varianza

```{r}
mod1 = aov(udc ~ genotipo, data = df1)
s_mod1 = summary(mod1)
p_valor = s_mod1[[1]][1,5]
ifelse(p_valor<0.05, 'Rechazo Ho', 'NO Rechazo Ho')
```

```{r}
# Prueba de Tukey - para comparación de medias
TukeyHSD(mod1, 'genotipo')

# Podemos concluir estadisticamente que todos los genotipos son diferentes en cuanto al contenido de canabinoide
```

```{r}
# Revisando supuestos del modelo

# Normalidad de residuales
shapiro.test(mod1$residuals)

# Igualdad de varianzas
bartlett.test(mod1$residuals, df1$genotipo)
```

```{r}
library(writexl)
write_xlsx(df, 'datos_CE_1001083581.xlsx')

library(openxlsx)
write.xlsx(df1, 'datos_CE_090522.xlsx')
```























